version: "3.8"
services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: db
  app:
    build: ./
    cache_from:
      - jaymes15/crypcentra-ico:latest
    image: jaymes15/crypcentra-ico:latest
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/app
      - ./app/data/web:/vol/web
    depends_on: 
      - db
    container_name: app

  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      - '6379'

    