# Generated by Django 3.0.14 on 2021-10-17 21:20

import core.model_validators.validate_date
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "number_of_available_token",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                (
                    "bidding_window",
                    models.DateTimeField(
                        validators=[core.model_validators.validate_date.validate_date]
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_tokens",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("bidding_price", models.PositiveIntegerField()),
                (
                    "token_recieved",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recieved some", "RECIEVED SOME"),
                            ("recieved all", "RECIEVED ALL"),
                            ("none", "None"),
                        ],
                        default="None",
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Coin"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
