# Generated by Django 3.0.14 on 2021-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210829_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('recieved some', 'RECIEVED SOME'), ('recieved', 'RECIEVED'), ('none', None)], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='bid',
            name='token_recieved',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
