# Generated by Django 3.0.14 on 2021-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210829_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('recieved some', 'RECIEVED SOME'), ('recieved', 'RECIEVED'), ('none', 'None')], default='None', max_length=30),
        ),
    ]
