# Generated by Django 3.0.14 on 2021-08-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210829_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('recieved some', 'RECIEVED SOME'), ('recieved all', 'RECIEVED ALL'), ('none', 'None')], default='None', max_length=30),
        ),
    ]
